name: CI Pipeline/Workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ci-build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: ${{secrets.IMAGE_NAME}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to dockerhub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: Build docker image
        run: docker build -t $DOCKERHUB_USERNAME/leetcode:latest .
      - name: Push docker image to dockerhub
        run: docker push $DOCKERHUB_USERNAME/leetcode:latest